### ISSUE TITLE
[Checklist] Implement The Xline Operator

### ISSUE THREAD

**Issue by iGxnon** [xline-kv/xline-operator#5]
## Background

We need to implement an operator for k8s (and possibly other platforms in the future, but mainly for k8s) to serve as a human operator that monitors the xline cluster, allowing human operators to focus on other critical tasks. This is a checklist to track the process of implementing the xline operator.

The operator should be highly available and capable of recovering the xline clusters and itself from inconsistent states. To achieve this, we have introduced an architecture for the Xline Operator as shown below:

![image](https://github.com/xline-kv/xline-operator/assets/59405399/42216856-0718-4d9a-8ed1-cc06635e375f)

More detailed designs will be discussed in the following checklist.

## Checklist

- Implement Deploy Operator
  - [x] Implement [CRD](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#customresourcedefinitions)'s rust binding, creation and updating on k8s. (Resolved in #1)
  - [ ] Implement the [Heartbeat HTTP Service]() in Deploy Operator to keep Sidecar Operator alive.
  - [ ] ⭐️ Implement the [Creating, Updating, Deleting steps]() of CRD.
  - [ ] (Optional) Implement the similar logic in other platform(such as [HashiCorp Nomad](https://developer.hashicorp.com/nomad)).

- Implement Sidecar Operator
  - [x] Implement the initial scripts to prepare environment(xline configuration file). (Resolved in #3)
  - [ ] Implement the [HTTP Service]() to expose the state to other sidecar operators.
  - [ ] ⭐️ Implement the structure and methods of [OperatorsProbe, KvserverHandle]() for each sidecar operator.
  - [ ] Implement the [Heartbeat Daemon]() for each sidecar operator.
  - [ ] Implement the [Evaluate and Reconcile]() process.

**Comment by liangyuanpeng** [comment]
I will suggest name the sidecar operator  to xline sidecar , and it's also managed by xline operator.

The sidecar operator makes people think that it manages the sidecar, but in fact it is just a sidecar.

For the first version, xline operator just work for deploy xline, sidecar is the advanced features and exist on the roadmap.

Some comment to FYI. :)

**Comment by iGxnon** [comment]
> I will suggest name the `sidecar operator` to `xline sidecar` , and it's also managed by `xline operator`.
> 
> The `sidecar operator` makes people think that it manages the sidecar, but in fact it is just a sidecar.
> 
> For the first version, xline operator just work for deploy xline, sidecar is the advanced features and exist on the roadmap.
> 
> Some comment to FYI. :)

Thanks for your reply.

This name `sidecar operator` is indeed not very appropriate, and I will make the necessary correction.

After our discussion, I think we can go with your suggestion for the first version. I will submit a PR to file this version in the future.
